CREATE DATABASE TICKET_BOOKING_SYSTEM;
USE TICKET_BOOKING_SYSTEM;



CREATE TABLE VENU(VENUE_ID INT PRIMARY KEY AUTO_INCREMENT,VENUE_NAME VARCHAR(20),ADDRESS VARCHAR(20));
CREATE TABLE EVENT_TB(EVENT_ID INT PRIMARY KEY AUTO_INCREMENT,EVENT_NAME VARCHAR(20),EVENT_DATE DATE,EVENT_TIME TIME,VENUE_ID INT,TOT_SEATS INT,AVAIL_SEATS INT,TKT_PRICE DECIMAL(12,2),EVENT_TYPE VARCHAR(20),BOOKING_ID INT);
CREATE TABLE CUSTOMER(CUST_ID INT PRIMARY KEY AUTO_INCREMENT,CUST_NAME VARCHAR(20),EMAIL VARCHAR(20),PH_NO VARCHAR(10));
CREATE TABLE BOOKING(BOOKING_ID INT PRIMARY KEY,CUST_ID INT,EVENT_ID INT,NUM_TICKETS INT,TOT_COST DECIMAL(12,2),BOOKING_DATE DATE);

ALTER TABLE EVENT_TB ADD CONSTRAINT FOREIGN KEY(VENUE_ID) REFERENCES VENU(VENUE_ID);
ALTER TABLE EVENT_TB ADD CONSTRAINT FOREIGN KEY(BOOKING_ID) REFERENCES BOOKING(BOOKING_ID);

ALTER TABLE BOOKING ADD CONSTRAINT FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID);
ALTER TABLE BOOKING ADD CONSTRAINT FOREIGN KEY(EVENT_ID) REFERENCES EVENT_TB(EVENT_ID);
ALTER TABLE CUSTOMER MODIFY COLUMN EMAIL VARCHAR(30);
ALTER TABLE EVENT_TB MODIFY COLUMN EVENT_NAME VARCHAR(45);

DESC VENU;
DESC EVENT_TB;
DESC CUSTOMER;
DESC BOOKING;